import type { Metadata } from "next"
import "./globals.css"
import { Footer, Navigation } from "@/components"

export const metadata: Metadata = {
	title: "DK",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className='bg-gradient-to-r from-blue-100 via-white to-blue-100 sm:bg-gradient-to-r sm:from-blue-100 sm:via-white sm:to-blue-200'>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	)
}
