import type { Metadata } from "next"
import "./globals.css"
import { Footer, Navigation } from "@/components"

export const metadata: Metadata = {
	title: "DK",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	)
}
